<a href="https://colab.research.google.com/github/18121a05l8/Easyecom_assignment/blob/main/Creating_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import absolute_import
from __future__ import print_function
from __future__ import division

import tensorflow as tf

In [4]:
ten = tf.random.normal([2,3,4],2,1)
print(ten)

tf.Tensor(
[[[ 2.3591003   3.924478    1.9957986   1.5840237 ]
  [ 2.1052017   1.6462998   2.8093176   2.3065953 ]
  [ 3.0374813   2.8344321   1.8001952   1.1931461 ]]

 [[ 3.2624083   2.5387187   2.9646502   3.8290107 ]
  [ 1.8132234  -0.25027943  2.8257606   0.35598338]
  [ 2.1425831   1.4351314   1.5402347   2.1957223 ]]], shape=(2, 3, 4), dtype=float32)


In [12]:
tf.multiply(ten,ten)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 5.5653543 , 15.401528  ,  3.983212  ,  2.5091312 ],
        [ 4.4318743 ,  2.710303  ,  7.8922653 ,  5.320382  ],
        [ 9.226293  ,  8.034005  ,  3.2407029 ,  1.4235977 ]],

       [[10.643308  ,  6.4450927 ,  8.78915   , 14.661324  ],
        [ 3.2877789 ,  0.06263979,  7.984923  ,  0.12672417],
        [ 4.5906625 ,  2.0596023 ,  2.3723228 ,  4.8211966 ]]],
      dtype=float32)>

In [13]:
tf.scalar_mul(2,ten)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 4.7182007 ,  7.848956  ,  3.9915972 ,  3.1680474 ],
        [ 4.2104034 ,  3.2925997 ,  5.618635  ,  4.6131907 ],
        [ 6.0749626 ,  5.6688643 ,  3.6003904 ,  2.3862922 ]],

       [[ 6.5248165 ,  5.0774374 ,  5.9293003 ,  7.6580215 ],
        [ 3.6264467 , -0.50055885,  5.651521  ,  0.71196675],
        [ 4.2851663 ,  2.8702629 ,  3.0804694 ,  4.3914447 ]]],
      dtype=float32)>

In [17]:
print(ten)
tf.abs(ten)

tf.Tensor(
[[[ 2.3591003   3.924478    1.9957986   1.5840237 ]
  [ 2.1052017   1.6462998   2.8093176   2.3065953 ]
  [ 3.0374813   2.8344321   1.8001952   1.1931461 ]]

 [[ 3.2624083   2.5387187   2.9646502   3.8290107 ]
  [ 1.8132234  -0.25027943  2.8257606   0.35598338]
  [ 2.1425831   1.4351314   1.5402347   2.1957223 ]]], shape=(2, 3, 4), dtype=float32)


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[2.3591003 , 3.924478  , 1.9957986 , 1.5840237 ],
        [2.1052017 , 1.6462998 , 2.8093176 , 2.3065953 ],
        [3.0374813 , 2.8344321 , 1.8001952 , 1.1931461 ]],

       [[3.2624083 , 2.5387187 , 2.9646502 , 3.8290107 ],
        [1.8132234 , 0.25027943, 2.8257606 , 0.35598338],
        [2.1425831 , 1.4351314 , 1.5402347 , 2.1957223 ]]], dtype=float32)>

In [18]:
tf.reciprocal(ten)

AttributeError: ignored